# Generated by Django 4.0.6 on 2022-08-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_supplement'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='carbohydrate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supplement',
            name='dha_epa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supplement',
            name='dietary_fiber',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supplement',
            name='energy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supplement',
            name='fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supplement',
            name='folic_acid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supplement',
            name='magnesium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supplement',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supplement',
            name='tryptophan',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supplement',
            name='vitamin_a',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supplement',
            name='vitamin_b12',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supplement',
            name='vitamin_b6',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supplement',
            name='vitamin_d',
            field=models.FloatField(default=0.0),
        ),
    ]
