# Generated by Django 4.0.6 on 2022-08-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='food',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='food',
            name='is_beverage',
        ),
        migrations.RemoveField(
            model_name='food',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(default='미분류', max_length=50),
            preserve_default=False,
        ),
    ]
