# Generated by Django 4.0.6 on 2022-08-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_remove_food_amount_remove_food_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='food',
            name='classifier',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(blank=True, to='foods.category'),
        ),
    ]
