# Generated by Django 4.0.6 on 2022-08-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_b_amount_post_breakfast_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='remark',
        ),
    ]
