# Generated by Django 4.0.6 on 2022-08-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pic1',
            new_name='breakfast_img',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pic2',
            new_name='dinner_img',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pic3',
            new_name='lunch_img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='supplement',
        ),
        migrations.RemoveField(
            model_name='post',
            name='supplement_amount',
        ),
        migrations.AddField(
            model_name='post',
            name='snack_img',
            field=models.ImageField(blank=True, upload_to='post/images/%Y/%m/%d'),
        ),
    ]
