# Generated by Django 4.0.6 on 2022-08-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_remove_category_slug_food_classifier_and_more'),
        ('posts', '0005_rename_pic1_post_breakfast_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='supplement',
            field=models.ManyToManyField(blank=True, related_name='supplement_food', to='foods.food'),
        ),
        migrations.AddField(
            model_name='post',
            name='supplement_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
