# Generated by Django 4.0.6 on 2022-08-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_supplement_post_supplement_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='breakfast_img',
            new_name='breakfast_img1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='dinner_img',
            new_name='breakfast_img2',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='lunch_img',
            new_name='breakfast_img3',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='snack_img',
            new_name='dinner_img1',
        ),
        migrations.AddField(
            model_name='post',
            name='dinner_img2',
            field=models.ImageField(blank=True, upload_to='post/images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='dinner_img3',
            field=models.ImageField(blank=True, upload_to='post/images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='lunch_img1',
            field=models.ImageField(blank=True, upload_to='post/images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='lunch_img2',
            field=models.ImageField(blank=True, upload_to='post/images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='lunch_img3',
            field=models.ImageField(blank=True, upload_to='post/images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='snack_img1',
            field=models.ImageField(blank=True, upload_to='post/images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='snack_img2',
            field=models.ImageField(blank=True, upload_to='post/images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='snack_img3',
            field=models.ImageField(blank=True, upload_to='post/images/%Y/%m/%d'),
        ),
    ]
