# Generated by Django 4.0.6 on 2022-08-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrient',
            old_name='vitamin_c',
            new_name='vitamin_a',
        ),
    ]
