# Generated by Django 4.0.6 on 2022-08-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='d_nutrient',
        ),
        migrations.RemoveField(
            model_name='user',
            name='m_nutrient',
        ),
        migrations.RemoveField(
            model_name='user',
            name='y_nutrient',
        ),
    ]
