# Generated by Django 4.0.6 on 2022-08-31 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_supplement_carbohydrate_supplement_dha_epa_and_more'),
        ('consumptions', '0012_supplementconsmption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplementconsmption',
            old_name='supplement_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='supplementconsmption',
            old_name='supplement_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='supplementconsmption',
            old_name='supplement_manufacturer',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='supplementconsmption',
            old_name='supplement_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='supplementconsmption',
            name='supplement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.supplement'),
        ),
    ]
