# Generated by Django 4.0.6 on 2022-09-07 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_supplement_carbohydrate_supplement_dha_epa_and_more'),
        ('consumptions', '0013_rename_supplement_amount_supplementconsmption_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementconsmption',
            name='supplement',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.supplement'),
        ),
    ]
